accessPolicy:
    inbound:
      rules:
        - application: vaktor-plan
    outbound:
      rules:
        - application: vaktor-plan
        - application: vaktor-mwt-mock
ingresses:
  - https://vaktor-lonn.dev.intern.nav.no
envs:
  - name: MINWINTID_INTERVAL
    value: 5m
replicas:
  min: 1
  max: 1