apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: navdig
  name: vaktor-lonn
  namespace: navdig
spec:
  accessPolicy:
    inbound:
      rules:
        - application: vaktor-plan
    outbound:
      rules:
        - application: vaktor-plan
      external:
        - host: tdv-p.adeo.no
          ports:
            - port: 9402
  image: {{image}}
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 32Mi
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
      allowAllUsers: false
      tenant: nav.no
  env:
  {{#each envs}}
    - name: {{this.name}}
      value: "{{this.value}}"
  {{/each}}
  envFrom:
    - secret: vaktor-lonn
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  gcp:
    sqlInstances:
      - databases:
        - name: vaktor-lonn
          envVarPrefix: DB
        type: POSTGRES_14
