apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: navdig
  name: vaktor-lonn
  namespace: navdig
spec:
  image: {{image}}
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
      allowAllUsers: false
      tenant: nav.no
  ingresses:
    - https://vaktor-lonn.dev.intern.nav.no
  gcp:
    sqlInstances:
      - databases:
        - name: vaktor-lonn
          envVarPrefix: DB
        type: POSTGRES_14
