apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: navdig
  name: vaktor-lonn
  namespace: navdig
spec:
  accessPolicy:
    inbound:
      rules:
        - application: vaktor-plan
    outbound:
      rules:
        - application: vaktor-plan
      external:
        - host: dvh.adeo.no
  image: {{image}}
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 32Mi
  observability:
    logging:
      destinations:
        - id: loki
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
      allowAllUsers: false
      tenant: nav.no
  envFrom:
    - secret: vaktor-lonn
  env:
    - name: VAKTOR_PLAN_ENDPOINT
      value: http://vaktor-plan/api/v1/salaries/
    - name: MINWINTID_ENDPOINT
      value: https://dvh.adeo.no/ords/dvh/dt_hr/vaktor/tiddata
    - name: MINWINTID_ORDS_ENDPOINT
      value: https://dvh.adeo.no/ords/dvh/oauth/token
  gcp:
    sqlInstances:
      - databases:
        - name: vaktor-lonn
          envVarPrefix: DB
        type: POSTGRES_14
        tier: db-f1-micro
