apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: navdig
  name: vaktor-lonn
  namespace: navdig
spec:
  accessPolicy:
    inbound:
      rules:
        - application: vaktor-plan
      external:
        - host: tdv-p.adeo.no
          ports:
            - port: 9402
  image: {{image}}
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 32Mi
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
      allowAllUsers: false
      tenant: nav.no
  envFrom:
    - secret: vaktor-lonn
  gcp:
    sqlInstances:
      - databases:
        - name: vaktor-lonn
          envVarPrefix: DB
        type: POSTGRES_14
