accessPolicy:
    inbound:
      rules:
        - application: vaktor-plan
    outbound:
      rules:
        - application: vaktor-plan
      external:
        - host: tdv-p.adeo.no
          ports:
            - port: 9402
replicas:
  min: 1
  max: 1
