apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: navdig
  name: vaktor-mwt-mock
  namespace: navdig
spec:
  accessPolicy:
    inbound:
      rules:
        - application: vaktor-lonn
  image: {{image}}
  replicas:
    min: 1
    max: 1
  ingresses:
    - https://vaktor-mwt-mock.dev.intern.nav.no
