apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: navdig
  name: vaktor-mwt-mock
  namespace: navdig
spec:
  image: {{image}}
  ingresses:
    - https://vaktor-mwt-mock.dev.intern.nav.no
