apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: vaktor
  name: vaktor-mwt-mock
  namespace: vaktor
spec:
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 64Mi
  accessPolicy:
    inbound:
      rules:
        - application: vaktor-lonn
