name: Deploy MWTmock

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-mock.yaml"
      - "MWTmock/**"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0 # Fetch all history for what-changed action
      - name: Determine what to do
        id: changed-files
        uses: nais/what-changed@bc3dad0463b36ad29044134bba5898f0af73c34c
        with:
          files: MWTmock/nais.yaml
      - name: Push docker image to GAR
        if: steps.changed-files.outputs.changed != 'only-inputs'
        uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5
        id: docker-build-push
        with:
          image_suffix: mwt-mock
          docker_context: MWTmock
          team: vaktor

  deploy:
    name: Deploy to NAIS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b
        env:
          CLUSTER: dev-gcp
          RESOURCE: MWTmock/nais.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
